import Head from 'next/head'
import Image from 'next/image'
import Nav from '../components/Nav'
import ProjectCard from '../components/ProjectCard'
import ContactForm from '../components/ContactForm'
import SkillsIconLink from '../components/SkillsIconLink'
import TopSvg from '../components/svgs/layered-waves-haikei.svg'
import Brushstroke from '../components/svgs/brushstroke_small.svg'
import BotSvg from '../components/svgs/layered-waves-haikei-bottom4.svg'
import {FaChevronDown, FaJava, FaCss3Alt, FaHtml5, FaJsSquare, FaPhp, FaGit} from 'react-icons/fa/'
import {IoLocationOutline} from 'react-icons/io5/'
import {DiScrum} from 'react-icons/di/'
import {SiTypescript, SiMysql, SiCplusplus, SiApachegroovy, SiAngular, SiNextdotjs, SiLaravel, SiGithub, SiGitlab, SiJirasoftware, SiTeamcity, SiPostman, SiSpring, SiSpringboot, SiIntellijidea, SiVisualstudiocode, SiDocker, SiLinux, SiTailwindcss, SiAdobephotoshop} from 'react-icons/si/'
import {AiFillLinkedin, AiFillFacebook, AiOutlineGithub} from 'react-icons/ai/'
import "animate.css"
import { Inter } from '@next/font/google'
import { InView } from 'react-intersection-observer';


const inter = Inter({ subsets: ['latin'] })

const iconStyle = "w-5/5 h-2/5 text-white sm:text-9xl sm:h-2/4";

export default function Home() {  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='snap-y snap-mandatory scroll-smooth h-screen w-full overflow-y-scroll'>
        <Nav />
        <section id="home" className='snap-start bg-lavaOrange w-full h-full flex flex-col justify-center overflow-hidden'>
          <h1 className="animate__animated animate__fadeInDown animate__fast mb-20 text-violet-500 uppercase font-extrabold text-center drop-shadow-lg text-5xl sm:text-9xl ">Colorful Code</h1>
          <h2 className="animate__animated animate__fadeIn animate__slow animateShortenDelay animate__delay-3s mb-20 text-zinc-800 lowercase font-light text-center text-sm sm:text-lg sm:font-normal">Bringing a human touch to technology</h2>
          <a className='animate__animated animate__fadeInUpBig animateDuration2100ms self-center' href="#about"><FaChevronDown className='animate__animated animate__shakeY animate__infinite animateDuration10s self-center text-4xl sm:text-6xl'/></a>
        </section>

        <InView triggerOnce={true} threshold={0}>
        {({ inView, ref, entry }) => (
          <section id="about" className='snap-start bg-amber-400 w-full h-full flex flex-col overflow-y-auto p-8'>
            <div ref={ref} className={`relative flex justify-center mb-4 ${inView ? 'animate__animated animate__slideInDown animate__fast' : 'hidden'}`}>
              <Brushstroke className="absolute w-1/2 h-1/2 top-1/2 fill-brightMustard"/>
              <h1 className='text-shadow-sm relative uppercase drop-shadow-lg text-white text-center font-semibold text-3xl mb-2 sm:text-9xl sm:mb-10 sm:text-shadow-lg'>About</h1>
            </div>
            <Image ref={ref} className={`self-center shadow-2xl w-70 h-70 object-fill rounded-md ${inView ? 'animate__animated animate__jackInTheBox animate__slow' : 'hidden'}`} src="/images/profile.jpg" width="200" height="0" alt="Picture of Amir" />
            <div ref={ref} className={`text-base space-y-6 my-6 self-center sm:mt-12 sm:mb-24 ${inView ? 'animate__animated animate__slideInUp animate__faster' : ''}`}>
              <p className="font-light text-gray-800">I'm the face behind Colorful Code, a 35 year old Software Engineer based in Sweden. At heart I'm a creative soul that is passionate about creating and problem solving. I also love to learn new things in life, so I try to stay curious and keep an open mind.</p>
              <p className="font-light text-gray-800">My clients can always expect a professional service with modern technological solutions. I also aim to create a fun and engaging work environment and elevate my peers when possible.</p>
              <p className="font-light text-gray-800">Outside of work I write and produce music, spend time with friends and family, hike, garden, exercise, travel, listen to podcasts etc. I wish there was more time in life because the list is long and it keeps growing! :D</p>
            </div>
              <h2 className='text-center font-normal text-xl text-md sm:text-4xl sm:mb-2 sm:font-light'>Tools I use</h2>
              <div className="flex justify-center">
                <div className="flex flex-wrap max-w-3xl p-2 justify-center gap-0 sm:gap-x-10 gap-y-4">
                  <SkillsIconLink url="https://www.java.com" icon={<FaJava className={iconStyle} />}/>
                  <SkillsIconLink url="https://www.w3.org/Style/CSS/Overview.en.html" icon={<FaCss3Alt className={iconStyle} />}/>
                  <SkillsIconLink url="https://www.javascript.com" icon={<FaJsSquare className={iconStyle} />}/>
                  <SkillsIconLink url="https://html.spec.whatwg.org/multipage" icon={<FaHtml5 className={iconStyle} />}/>
                  <SkillsIconLink url="https://www.typescriptlang.org" icon={<SiTypescript className={iconStyle} />}/>
                  <SkillsIconLink url="https://www.php.net" icon={<FaPhp className={iconStyle} />}/>
                  <SkillsIconLink url="https://www.mysql.com" icon={<SiMysql className={iconStyle} />}/>
                  <SkillsIconLink url="https://isocpp.org" icon={<SiCplusplus className={iconStyle} />}/>
                  <SkillsIconLink url="https://groovy-lang.org" icon={<SiApachegroovy className={iconStyle} />}/>
                  <SkillsIconLink url="https://angular.io" icon={<SiAngular className={iconStyle} />}/>
                  <SkillsIconLink url="https://nextjs.org" icon={<SiNextdotjs className={iconStyle} />}/>
                  <SkillsIconLink url="https://laravel.com" icon={<SiLaravel className={iconStyle} />}/>
                  <SkillsIconLink url="https://github.com" icon={<SiGithub className={iconStyle} />}/>
                  <SkillsIconLink url="https://git-scm.com" icon={<FaGit className={iconStyle} />}/>
                  <SkillsIconLink url="https://about.gitlab.com" icon={<SiGitlab className={iconStyle} />}/>
                  <SkillsIconLink url="https://www.atlassian.com/software/jira" icon={<SiJirasoftware className={iconStyle} />}/>
                  <SkillsIconLink url="https://www.jetbrains.com/teamcity" icon={<SiTeamcity className={iconStyle} />}/>
                  <SkillsIconLink url="https://www.scrum.org" icon={<DiScrum className={iconStyle} />}/>
                  <SkillsIconLink url="https://www.postman.com" icon={<SiPostman className={iconStyle} />}/>
                  <SkillsIconLink url="https://spring.io" icon={<SiSpring className={iconStyle} />}/>
                  <SkillsIconLink url="https://spring.io/projects/spring-boot" icon={<SiSpringboot className={iconStyle} />}/>
                  <SkillsIconLink url="https://www.jetbrains.com/idea" icon={<SiIntellijidea className={iconStyle} />}/>
                  <SkillsIconLink url="https://code.visualstudio.com" icon={<SiVisualstudiocode className={iconStyle} />}/>
                  <SkillsIconLink url="https://www.docker.com" icon={<SiDocker className={iconStyle} />}/>
                  <SkillsIconLink url="https://www.linux.org" icon={<SiLinux className={iconStyle} />}/>
                  <SkillsIconLink url="https://tailwindcss.com" icon={<SiTailwindcss className={iconStyle} />}/>
                  <SkillsIconLink url="https://www.adobe.com/products/photoshop.html" icon={<SiAdobephotoshop className={iconStyle} />}/>
                </div>
              </div>
          </section>
        )}
        </InView>

        <InView triggerOnce={true} threshold={0}>
        {({ inView, ref, entry }) => (
          <section id="projects" className='snap-start bg-teal-500  w-full h-full flex flex-col overflow-y-auto p-8'>
            <div ref={ref} className={`relative flex justify-center mb-4 ${inView ? 'animate__animated animate__slideInLeft animate__faster' : ''}`}>
              <Brushstroke className="absolute w-1/2 h-1/2 top-1/2 fill-green-300"/>
              <h1 className='text-shadow-sm relative uppercase drop-shadow-lg text-white text-center font-semibold text-3xl mb-2 sm:text-9xl sm:mb-10 sm:text-shadow-lg'>Projects</h1>
            </div>
            <p ref={ref} className={`text-xs font-thin self-center mb-2 ${inView ? 'animate__animated animate__slideInRight animate__faster' : ''}`}> Most of my work are things I can not share here due to client confidentiality. However, I have more personal projects that will be added soon.</p>
            <div ref={ref} className={`flex flex-wrap grow gap-y-10 gap-x-20 justify-center overflow-y-auto ${inView ? 'animate__animated animate__slideInLeft animate__faster' : ''}`}>
              <ProjectCard imageName="teaguide" imageAlt="Image of this site" header="This portfolio site" repoName="nextjs-portfolio-site" siteUrl="https://www.colorfulcode.se" tools={["NextJS", "React", "CSS", "TailwindCSS", "HTML", "Animate.css", "FormCarry"]} text="A single page application to showcase my projects and promote my business. I wanted to learn some new frameworks with this project so I wrote this site using NextJS and Tailwind."/>
              <ProjectCard imageName="teaguide" imageAlt="Image of word search site" header="Word search" repoName="" siteUrl="" tools={["Spring Boot", "Java", "React", "NextJS"]} text="Currently under construction."/>
              <ProjectCard imageName="teaguide" imageAlt="Image of word search site" header="Word search" repoName="" siteUrl="" tools={["Spring Boot", "Java", "React", "NextJS"]} text="Currently under construction."/>
              <ProjectCard imageName="teaguide" imageAlt="Image of word search site" header="Word search" repoName="" siteUrl="" tools={["Spring Boot", "Java", "React", "NextJS"]} text="Currently under construction."/>
              <ProjectCard imageName="teaguide" imageAlt="Image of word search site" header="Word search" repoName="" siteUrl="" tools={["Spring Boot", "Java", "React", "NextJS"]} text="Currently under construction."/>
              <ProjectCard imageName="teaguide" imageAlt="Image of word search site" header="Word search" repoName="" siteUrl="" tools={["Spring Boot", "Java", "React", "NextJS"]} text="Currently under construction."/>
              <ProjectCard imageName="teaguide" imageAlt="Image of word search site" header="Word search" repoName="" siteUrl="" tools={["Spring Boot", "Java", "React", "NextJS"]} text="Currently under construction."/>
              <ProjectCard imageName="teaguide" imageAlt="Image of word search site" header="Word search" repoName="" siteUrl="" tools={["Spring Boot", "Java", "React", "NextJS"]} text="Currently under construction."/>
            </div>
          </section>
        )}
        </InView>

        <InView triggerOnce={true} threshold={0}>
        {({ inView, ref, entry }) => (
          <section id="contact" className='snap-start bg-indigo-500 w-full h-full flex flex-col align-middle overflow-y-auto p-8'>
            <div ref={ref} className={`relative flex justify-center mb-4 ${inView ? 'animate__animated animate__zoomIn animate__fast' : ''}`}>
                <Brushstroke className="absolute w-1/2 h-1/2 top-1/2 fill-red-400"/>
                <h1 className='text-shadow-sm relative uppercase drop-shadow-lg text-white text-center font-semibold text-3xl mb-2 sm:text-9xl sm:mb-10 sm:text-shadow-lg'>Contact</h1>
              </div>

            {/* Main container in this section */}
            <div ref={ref} className={`flex flex-wrap self-center space-y-4 w-full shadow-2xl rounded-lg border border-slate-600 sm:w-fit p-2 ${inView ? 'animate__animated animate__slideInUp animate__faster' : ''}`}>
              <div ref={ref} className={`flex w-full justify-center mt-4 ${inView ? 'animate__animated animate__flipInX animateShortenDelay animate__delay-2s' : ''}`}>
                <h2 className="text-center text-xs font-bold shadow-lg border-2 rounded-lg border-green-400 bg-green-100 p-2">Currently available for new contracts.</h2>
              </div>
              {/* Container for contact form and address/icons */}
              <div className='flex flex-wrap w-full justify-center p-2'>
                  <div className='flex max-w-xl'>
                    <ContactForm bgColor="bg-indigo-500" sendBtnBorder="border-indigo-600 " sendBtnBg="bg-indigo-200" />   
                  </div>
                  <div className='flex grow flex-col h-auto self-center mt-8 space-y-10'>
                    <div className="flex items-center justify-center">
                      <IoLocationOutline className='text-lg text-black mr-4'/>
                      <div className="max-w-fit">
                        <div className="max-w-fit font-light text-black tracking-wide">Colorful Code</div>
                        <div className="max-w-fit font-light text-black tracking-wide">Gullbergsgatan 6</div>
                        <div className="max-w-fit font-light text-black tracking-wide">58246 Linköping</div>
                        <div className="max-w-fit font-light text-black tracking-wide">Sweden</div>
                      </div>
                    </div>
                    <div className='flex justify-center space-x-8 sm:justify-center sm:space-x-12'>         
                      <a href="https://www.linkedin.com/in/colorfulcode/" target="_blank" className='flex justify-center align-middle shadow-md bg-gray-700 rounded-md'>
                        <AiFillLinkedin className='text-4xl fill-red-300'/>
                      </a>   
                      <a href="https://www.facebook.com/AmicciUntzUntz" target="_blank" className='flex justify-center align-middle shadow-md bg-gray-700 rounded-md'>
                        <AiFillFacebook className='text-4xl fill-amber-400'/>
                      </a>   
                      <a href="https://github.com/colorful-code" target="_blank" className='flex justify-center align-middle shadow-md bg-gray-700 rounded-md'>
                        <AiOutlineGithub className='text-4xl fill-teal-400'/>
                      </a>   
                    </div>
                  </div>
              </div>
            </div>
          </section>
        )}
        </InView>
      </main>
    </>
  )
}
