import Head from 'next/head'
import Nav from '../components/Nav'
import { Inter } from '@next/font/google'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      
      <main className='snap-y snap-mandatory scroll-smooth h-screen w-screen overflow-scroll'>
        <Nav />
        <section id="blob" className='snap-start bg-amber-200 w-screen h-screen flex items-center justify-center text-8xl'>1</section>
        <section id="about" className='snap-start bg-teal-200 w-screen h-screen flex items-center justify-center text-8xl'>2</section>
        <section id="projects" className='snap-start bg-cyan-400 w-screen h-screen flex items-center justify-center text-8xl'>3</section>
        <section id="contact" className='snap-start bg-fuchsia-200 w-screen h-screen flex items-center justify-center text-8xl'>4</section>

      </main>

    </>
  )
}
